package com.sunbeaminfo.LibraryManagement.enums;

public enum eLibrarian 
{
	EXIT,EDITPROFILE,EDITPASSWORD,RETURN_COPY,ISSUE_COPY,FIND_BOOK,EDITBOOK,ADD_NEW_BOOK,CHECK__AVAILABILTY,
	ADD_NEW_COPY,CHANGE_RACK,ADD_NEW_MEMBER,TAKE_PAYMENT

}
